custom-commands:
  - name: config
    help: Set values in config files
    options:
      - name: debug
        short: d
        type: COUNTER
        help: Show DEBUG log events.
      - name: file
        short: f
        type: STRING
        help: Config file
        default: ~/.jira.d/config.yml
      - name: compact
        short: c
        type: BOOL
        help: Minified JSON
        default: false
    args:
      - name: ITEM
        type: STRINGMAP
    script: |
      JIRA_SCRIPT=config \
      JIRA_OPT={{options | toMinJson | shellquote}} \
      JIRA_ARG={{args | toMinJson | shellquote}} \
        exec {{jira}}-scripts
  - name: sync
    help: Sync issue documents.
    options:
      - name: debug
        short: d
        type: COUNTER
        help: Show DEBUG log events.
    args:
      - name: DOC
        repeat: true
        required: true
    script: |
      JIRA_SCRIPT=sync \
      JIRA_OPT={{options | toMinJson | shellquote}} \
      JIRA_ARG={{args | toMinJson | shellquote}} \
        exec {{jira}}-scripts
